openapi: 3.0.0
info:
  title: Contacts and Auth API
  version: 1.0.0
  description: API for managing contacts and user authentication
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-4-1czg.onrender.com
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    NotFound:
      $ref: './swagger/components/responses/notFound.yaml'
    Unauthorized:
      $ref: './swagger/components/responses/unauthorized.yaml'
  schemas:
    Contact:
      $ref: './swagger/components/schemas/contacts.yaml'
    Auth:
      $ref: './swagger/components/schemas/auth.yaml'
paths:
  /contacts:
    get:
      $ref: './swagger/path/contacts/get.yaml'
      tags:
        - Contacts
    post:
      $ref: './swagger/path/contacts/post.yaml'
      tags:
        - Contacts
  /contacts/{contactId}:
    get:
      $ref: './swagger/path/contacts/{id}/get.yaml'
      tags:
        - Contacts
    patch:
      $ref: './swagger/path/contacts/{id}/patch.yaml'
      tags:
        - Contacts
    delete:
      $ref: './swagger/path/contacts/{id}/delete.yaml'
      tags:
        - Contacts
  /auth/register:
    post:
      $ref: './swagger/path/auth/register.yaml'
      tags:
        - Auth
  /auth/login:
    post:
      $ref: './swagger/path/auth/login.yaml'
      tags:
        - Auth
  /auth/logout:
    post:
      $ref: './swagger/path/auth/logout.yaml'
      tags:
        - Auth
  /auth/refresh:
    post:
      $ref: './swagger/path/auth/refresh.yaml'
      tags:
        - Auth
  /auth/send-reset-email:
    post:
      $ref: './swagger/path/auth/send-reset-email.yaml'
      tags:
        - Auth
  /auth/reset-pwd:
    post:
      $ref: './swagger/path/auth/reset-pwd.yaml'
      tags:
        - Auth
