openapi: 3.0.0
security:
  - bearerAuth: []
info:
  title: Contacts API
  version: 1.0.0
  description: API for managing contacts
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: http://localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    NotFound:
      $ref: './swagger/components/responses/notFound.yaml'
  schemas:
    Contact:
      $ref: './swagger/components/schemas/contacts.yaml'
paths:
  /contacts:
    get:
      $ref: './swagger/path/contacts/get.yaml'
    post:
      $ref: './swagger/path/contacts/post.yaml'
  /contacts/{contactId}:
    get:
      $ref: './swagger/path/contacts/{id}/get.yaml'
    patch:
      $ref: './swagger/path/contacts/{id}/patch.yaml'
    delete:
      $ref: './swagger/path/contacts/{id}/delete.yaml'
